TILES-3943 Add route case
2gis/mapsapi pull request #556
Opened 2021-12-09 08:13 UTC by Kuznecoff

2021-12-10 05:02 UTC, Trufi commented
Добавь описание и как посмотреть. Я открыл нашу стандартную демку и у меня ничего не нарисовалось, хотя там как раз 1 маркер.

2021-12-10 05:02 UTC, Trufi requested changes

2021-12-10 05:05 UTC, Trufi commented on src/DGAttribution/src/DGAttribution.js
> +            if (layer._icon && _map.getBounds().contains(layer._latlng)) {
А что если слоев и особенно маркеров будет 1000? Делать такие проверки на каждый `moveend` не будет ли долго?

Может нужный маркер получать в обработчике `layeradd`? Если маркеров больше 1, то делать его undefined. В `layerremove` чекать его удаление, а в `moveend` вызывать `contains` только у одного маркера, если он есть.

2021-12-10 05:59 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +            if (layer._icon && _map.getBounds().contains(layer._latlng)) {
Попробую

2021-12-10 06:13 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +            if (layer._icon && _map.getBounds().contains(layer._latlng)) {
Ок норм идея. темболее что layeradd layerremove я уже отслеживаю

2021-12-10 07:22 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +            if (layer._icon && _map.getBounds().contains(layer._latlng)) {
Немного поменял, но если маркеров 1000 будет дергать каждый раз но только маркеры - там проверяет какие маркеры сейчас в видимости экрана их может быть 1000 но видно сейчас только один - тогда логичо что проехать к нему кнопку можно показать,

2021-12-10 07:25 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +            if (layer._icon && _map.getBounds().contains(layer._latlng)) {
можно в index.html добавить еще пару маркеров подальше и посмотреть как будет меняться кнопка - я так тестировал: если видно несколько маркеров одновременно то будет кнопка "Открыть... если видно только один маркер то кнопка "Доехать...
Добавил линки для зумов если unproject

2021-12-10 10:09 UTC, artem-malko commented on config.main.json
> +    "openLink2gis":  "{gislink}/center/{center}/zoom/{zoom}/openLink=true",
Не совсем понял, какая ссылка в итоге получится?

Просто в онайлне координаты и зум в query-части. Слагов center и zoom нет

2021-12-10 10:09 UTC, artem-malko commented on config.main.json
> +    "openLink2gis":  "{gislink}/center/{center}/zoom/{zoom}/openLink=true",
тот же вопрос про ссылку выше

2021-12-10 10:13 UTC, Kuznecoff commented on config.main.json
> +    "openLink2gis":  "{gislink}/center/{center}/zoom/{zoom}/openLink=true",
Примеры: 

http://2gis.ru/center/82.89689093828201,54.97947773210846/zoom/18/routeTab/rsType/bus/to/82.897440725094,54.980156831455/openLink=true
http://2gis.ru/center/82.89838761091234,54.97849876432055/zoom/18/openLink=true
Так работает зум и центр - и темплейт скопировал из темплейтов ниже и чуть допилил

2021-12-10 10:14 UTC, Kuznecoff commented on config.main.json
> +    "openLink2gis":  "{gislink}/center/{center}/zoom/{zoom}/openLink=true",
"ppnotLink": "http://2gis.{domain}/{projectCode}/center/{center}/zoom/{zoom}/routeTab/rsType/{rsType}/to/{point}╎{name}",

2021-12-10 10:22 UTC, artem-malko commented on config.main.json
> +    "openLink2gis":  "{gislink}/center/{center}/zoom/{zoom}/openLink=true",
Давай все же сделаем норм сслыки? Сейчас просто у нас где-то глубоко есть редиректор с таких урлов. Но, сколько он еще проживет — пес его знает.

https://2gis.ru/novosibirsk?m=82.898388%2C54.978499%2F18

https://2gis.ru/novosibirsk/directions/tab/bus/points/%7C82.897441%2C54.980157?m=82.896891%2C54.979478%2F18

2021-12-10 10:24 UTC, itanka9 commented on src/DGAttribution/src/DGAttribution.js
> +                this._markers = [];
А почему мы здесь полностью обнуляем массив маркеров, а не просто удаляем один удаляемый слой?

2021-12-10 10:24 UTC, itanka9 commented on src/DGAttribution/src/DGAttribution.js
> +                this._map.eachLayer(function (layer) {
И вот этот код зачем? Тут же, по-моему вовсе нет переменной markerLayers, куда пушатся маркеры.

2021-12-10 10:24 UTC, itanka9 commented on config.main.json
> +    "ppnotLink2gis": "{gislink}/center/{center}/zoom/{zoom}/routeTab/rsType/{rsType}/to/{point}/openLink=true",
А договорились давать ссылку именно на маршрут общественного транспорта? Тут просто используется аббревиатура ppnot.

2021-12-10 10:24 UTC, itanka9 commented on src/DGAttribution/src/DGAttribution.js
> +        var isNotTranslate = btn.label == 'open_on' || btn.label == 'route_on';
Уточни, плиз, что делает эта переменная?

2021-12-10 10:26 UTC, Kuznecoff commented on config.main.json
> +    "ppnotLink2gis": "{gislink}/center/{center}/zoom/{zoom}/routeTab/rsType/{rsType}/to/{point}/openLink=true",
там выбор на зуме до 12 будет для машины выше 12 для автобусов

2021-12-10 10:29 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +        var isNotTranslate = btn.label == 'open_on' || btn.label == 'route_on';
проверка есть перевод для этой кнопки для текущего язка или нету, потом проверяем если нету то кнопку не показываем вообще, например для чехии и украины нету кнопки открыть.
Было решение в ТЗ показывать только для России и для Эмиратов , для Эмиратов на английском кнопку написать.

2021-12-10 10:32 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +                this._map.eachLayer(function (layer) {
оу тут ошибка! this._markers должно было быть. Спасибо

2021-12-10 10:48 UTC, itanka9 commented on config.main.json
> +    "ppnotLink2gis": "{gislink}/center/{center}/zoom/{zoom}/routeTab/rsType/{rsType}/to/{point}/openLink=true",
Лучше назвать тогда этот параметр ppLink2gis, а то ppnotLink2gis введет в заблуждение что это только про маршрут на ОТ.

2021-12-10 10:48 UTC, itanka9 commented on src/DGAttribution/src/DGAttribution.js
> +        var isNotTranslate = btn.label == 'open_on' || btn.label == 'route_on';
Назови тогда хоть buttonNotTranslated и эту логику комментом опиши, а то непонятно.

2021-12-10 10:48 UTC, itanka9 commented on src/DGAttribution/src/DGAttribution.js
> +            'logotype': isNotTranslate || this._logotype,
А показ/скрытие кнопки вот через этот параметр делается?

2021-12-10 11:00 UTC, Trufi commented on src/DGAttribution/src/DGAttribution.js
> +                markerLayers.push(this._markers[i])
Получается сейчас, если маркеров много и я драгаю карту туда-сюда, то кнопка будет то одна, то другая? Давай упростим всю задачу и будет "Проехать" показывать, только когда маркер реально 1 на все карте, а не только во вьюпорте?

2021-12-10 11:39 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +            'logotype': isNotTranslate || this._logotype,
Да.

2021-12-10 11:39 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +                markerLayers.push(this._markers[i])
ок.

2021-12-10 11:41 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +                markerLayers.push(this._markers[i])
Если маркер сдвинули и его не видно но он есть тоже показывать "Доехать" ?

2021-12-13 08:25 UTC, Kuznecoff commented on config.main.json
> +    "openLink2gis":  "{gislink}/center/{center}/zoom/{zoom}/openLink=true",
ок мои линки поправил, там есть еще два старых линка - ссыкотно их править вдруг кто завязался на их структуру.

2021-12-13 08:27 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +                this._markers = [];
переделал упростил до одного маркера. удаление переделал, но под старый JS тут еще все на var тащить filter не стал

2021-12-13 08:27 UTC, Kuznecoff commented on config.main.json
> +    "ppnotLink2gis": "{gislink}/center/{center}/zoom/{zoom}/routeTab/rsType/{rsType}/to/{point}/openLink=true",
переименовал и линк переделал на современный как Артем писал

2021-12-13 08:27 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +        var isNotTranslate = btn.label == 'open_on' || btn.label == 'route_on';
назвал комент дописал

2021-12-13 08:29 UTC, Kuznecoff commented on src/DGAttribution/src/DGAttribution.js
> +                markerLayers.push(this._markers[i])
сделал вообще прям потупому, один маркер - мы Доехать, нет маркеров или много то Открыть, и вообще не смотрит есть он на карте нету.

2021-12-13 10:14 UTC, itanka9 approved these changes

2021-12-13 10:23 UTC, Trufi requested changes

2021-12-13 10:23 UTC, Trufi commented on src/DGAttribution/src/DGAttribution.js
> +        this._update();
Мы можем тут какой-нибудь throttle заиспользовать? Сейчас при создании и удалении **_любого_** слоя, мы будем вызывать пересоздание HTML контейнера с копирайтом.

2021-12-14 04:55 UTC, Trufi commented on src/DGAttribution/src/DGAttribution.js
> +                this._checkMarkerLayers();
```suggestion
                    this._checkMarkerLayers();
```

2021-12-14 06:12 UTC, Trufi approved these changes

2021-12-15 03:36 UTC, Trufi commented
А теперь самый главный вопрос — как ты тестировал финальный код? :)

2021-12-16 07:59 UTC, merged